### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Preisschild** [friimaind/pi-hole-droid#20]
Hey, can you please publish pi-hole-droid also to f-droid.net? A lot of people dont like to use GoogleApps and have no playstore.

**Comment by Rudloff** [comment]
There is a ticket for this here: https://gitlab.com/fdroid/rfp/issues/48

**Comment by Preisschild** [comment]
@Rudloff the ticker is already a year old and it seems that no process has been made.

**Comment by Rudloff** [comment]
F-Droid is seriously understaffed right now and we have a huge list of apps waiting to be packaged.
But I will have a look at this one.

**Comment by theel0ja** [comment]
~~maybe @IzzySoft could add it to [his repository](https://android.izzysoft.de/repo).~~

Oh nevermind, it's already there!

https://android.izzysoft.de/repo/apk/friimaind.piholedroid

**Comment by theel0ja** [comment]
Oh nevermind, it's already there!

https://android.izzysoft.de/repo/apk/friimaind.piholedroid

**Comment by IzzySoft** [comment]
:smiley: for more than a year actually (InRepoSince: 2017-04-25) :smiley:

Looks like before it can be listed in the official repo, someone needs to solve #21 here. It was opened by Pierre half a year ago and not even responded to; seems this crew is as understaffed as ours, or more …

**Comment by Preisschild** [comment]
Last commit one and a half year ago, so maybe this here is discontinued

**Comment by IzzySoft** [comment]
That might explain the missing responses.

**Comment by Rudloff** [comment]
Now that https://github.com/friimaind/pi-hole-droid/pull/21 is merged, we just need to wait for a new release :slightly_smiling_face:

**Comment by IzzySoft** [comment]
@friimaind could you please tag a new release? That's all F-Droid needs to get the stuck packaging request (stuck for almost a year now) done. Thanks!

**Comment by friimaind** [comment]
Done! https://github.com/friimaind/pi-hole-droid/releases/tag/1.0.5

Sorry guys but this project is unmaintained but I will be glad to help you as much as I can.
I'm really busy at work and I've got a daughter recently so maybe in the future, who knows :)

Apologize again for the delay

**Comment by IzzySoft** [comment]
Thanks @friimaind! I've updated the issue on our end and asked Rudloff to give it another try.

**Comment by Rudloff** [comment]
This can be closed.

**Comment by theel0ja** [comment]
https://f-droid.org/en/packages/friimaind.piholedroid/

**Comment by IzzySoft** [comment]
@friimaind could you please update the readme to point to the official repo? It still points to mine, where it now gets a 404. Thanks!

@Rudloff could you please take a look why 1.0.5 is not detected?

```yaml
AutoUpdateMode: Version %v
UpdateCheckMode: Tags
CurrentVersion: 1.0.4
CurrentVersionCode: 10004
```

Last tag here is `1.0.5`.

**Comment by friimaind** [comment]
> @friimaind could you please update the readme to point to the official repo? It still points to mine, where it now gets a 404. Thanks!

Sure, done!

Thank you

**Comment by Rudloff** [comment]
> @Rudloff could you please take a look why 1.0.5 is not detected?

Probably because the version code is dynamic: https://github.com/friimaind/pi-hole-droid/blob/8815af196cac64ce98c662f8f8110b4e58df1453/platforms/android/build.gradle#L168

**Comment by IzzySoft** [comment]
Aw, yeah. That won't work then.

@friimaind we need static numbers there. Or an alternative check method (like a specific file which looks like

```
versionCode: 55
versionName: 1.2.3
```

and matches the corresponding tag.

**Comment by m00head** [comment]
@friimaind @Rudloff Unfortunately it appears that my pull request hasn't fixed this issue - this file is not updating:
https://gitlab.com/Rudloff/fdroiddata/blob/develop/metadata/friimaind.piholedroid.yml

I believe this is because the tag / release for `1.0.5` is still on an older commit.

@friimaind Please will you delete the 1.0.5 tag and release, and recreate them on my latest commit? The following 2 links will be useful to help you do this:

https://www.abeautifulsite.net/how-to-delete-a-tag-on-github

https://help.github.com/en/github/administering-a-repository/editing-and-deleting-releases
