### ISSUE TITLE
Pi-hole API will change at some point

### ISSUE THREAD

**Issue by DL6ER** [friimaind/pi-hole-droid#7]
The API answers will change in the near future.
Please have a look at https://github.com/pi-hole/AdminLTE/pull/408

We can add something like `api.php?version` which will either respond with `PHP` or `FTL` if you like.

**Comment by friimaind** [comment]
Yes, that could be great thank you.

I will obviously adapt my app to use the new API version when it will be available.

**Comment by DL6ER** [comment]
`http://pi.hole/admin/api.php?type`

Currently:
```
[]
```

FTL-integration branch:
```
{"version":"FTL"}
```

FTL-integration branch, FTL not running (fallback mode):
```
{"version":"PHP"}
```

https://github.com/pi-hole/AdminLTE/commit/e3d791abb65c1a4634a8b6eccc6af20753d4e0fa

**Comment by DL6ER** [comment]
Have a look at 

https://discourse.pi-hole.net/t/pi-hole-api/1863

**Comment by DL6ER** [comment]
As of web `v2.5` you can already use these keywords for detecting what to do:

`http://pi.hole/admin/api.php?version` -> `{"version":2}`
`http://pi.hole/admin/api.php?version&type` -> `{"type":"PHP","version":2}`

etc.
