### ISSUE TITLE
Token as QR-Code

### ISSUE THREAD

**Issue by DL6ER** [friimaind/pi-hole-droid#8]
If you are willing to implement this, I can look into adding a QR code (or something similar) on the settings page which can be used to transfer the password token painlessly to your app.

**Comment by friimaind** [comment]
QR code could be awesome, I would really appreciate it!

EDIT: I'm saving this https://www.npmjs.com/package/cordova-plugin-qrscanner here.

**Comment by DL6ER** [comment]
![screenshot at 2017-02-20 12-18-27](https://cloud.githubusercontent.com/assets/16748619/23122962/b7d910ae-f766-11e6-8404-94d6fb7bac6e.png)

Used password was/is:
```
Test
```

**Comment by DL6ER** [comment]
New QR code (less error-correction, (25% instead of 30%) with much faster generation):

![screenshot at 2017-02-20 12-27-56](https://cloud.githubusercontent.com/assets/16748619/23123295/1c8821f6-f768-11e6-9cb6-bf65079b9b42.png)

**Comment by friimaind** [comment]
That's good, I see that you pass also "WEBPASSWORD=" 

Do you think that it's possible to pass *only* the string after "=", so this:

> WEBPASSWORD=123456

become this:

> 123456

**Comment by DL6ER** [comment]
Sure that is possible, I'd though about it as a security measure for you so people cannot scan just *something*. Let me know what you prefer.

**Comment by friimaind** [comment]
I think that you can pass only the string, there's no security problem on app side :+1:

**Comment by SnaKKo** [comment]
I suggest to use Google Charts:

https://developers.google.com/chart/infographics/docs/qr_codes

Example:

https://chart.googleapis.com/chart?chs=450x450&cht=qr&chl=123456&choe=UTF-8

**Comment by DL6ER** [comment]
Why use an external service for this when we can do everything locally?

New QR code:
![screenshot at 2017-02-20 12-37-21](https://cloud.githubusercontent.com/assets/16748619/23123601/55fccb34-f769-11e6-9841-f55ca2892df4.png)

**Comment by DL6ER** [comment]
PR: https://github.com/pi-hole/AdminLTE/pull/410

**Comment by DL6ER** [comment]
The pull request has been merged and the API token will be available with Pi-hole web interface v2.5 (to be released within the next few days).

**Comment by friimaind** [comment]
Thank you @DL6ER for the follow up!

**Comment by friimaind** [comment]
@DL6ER I've just released Pi-hole Droid 1.0.2 with QR Code scanner, thank you again for your help!
